[package]
name = "test_lalrpop"
version = "0.1.0"
authors = ["Joris Rehm <joris.rehm@wakusei.fr>"]
build = "build.rs" # LALRPOP preprocessing

# Add a dependency on the LALRPOP runtime library:
[dependencies.lalrpop-util]
version = "0.9.0"

[build-dependencies.lalrpop]
version = "0.9.0"